const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  readEnv: () => ipcRenderer.invoke('read-env'),
  import: (testCases) => ipcRenderer.invoke('import', testCases),
  onImportOutput: (cb) => ipcRenderer.on('import-output', (_, data) => cb(data)),
  offImportOutput: () => ipcRenderer.removeAllListeners('import-output'),
  generateReport: (data) => ipcRenderer.invoke('generate-report', data),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  getFolders: (data) => ipcRenderer.invoke('get-folders', data),
  getCycle: (data) => ipcRenderer.invoke('get-cycle', data),
  updateExecution: (data) => ipcRenderer.invoke('update-execution', data),
  linkCycleToIssue: (data) => ipcRenderer.invoke('link-cycle-to-issue', data),
  addToCycle: (data) => ipcRenderer.invoke('add-to-cycle', data),
  removeExecution: (data) => ipcRenderer.invoke('remove-execution', data),
  createCycle: (data) => ipcRenderer.invoke('create-cycle', data),
  generateCycleReport: (data) => ipcRenderer.invoke('generate-cycle-report', data),
  generateFullReport: (data) => ipcRenderer.invoke('generate-full-report', data),
  onCycleOutput: (cb) => ipcRenderer.on('cycle-output', (_, data) => cb(data)),
  offCycleOutput: () => ipcRenderer.removeAllListeners('cycle-output'),
  aiGenerateSession: (data) => ipcRenderer.invoke('ai-generate-session', data),
  saveSession: (data) => ipcRenderer.invoke('save-session', data),
  updateSession: (data) => ipcRenderer.invoke('update-session', data),
  loadSessions: () => ipcRenderer.invoke('load-sessions'),
  deleteSession: (id) => ipcRenderer.invoke('delete-session', id),
  analyzeBranch: (data) => ipcRenderer.invoke('analyze-branch', data),
  featureWriterRun: (data) => ipcRenderer.invoke('feature-writer-run', data),
  featureWriterSyncS3: (data) => ipcRenderer.invoke('feature-writer-sync-s3', data),
  featureWriterCreateBucket: () => ipcRenderer.invoke('feature-writer-create-bucket'),
  featureWriterCreateSentinels: (data) => ipcRenderer.invoke('feature-writer-create-sentinels', data),
  onFeatureWriterOutput: (cb) => ipcRenderer.on('feature-writer-output', (_, data) => cb(data)),
  offFeatureWriterOutput: () => ipcRenderer.removeAllListeners('feature-writer-output'),
  zephyrSearchTestCases: (data) => ipcRenderer.invoke('zephyr-search-test-cases', data),
  metricsGenerate: (data) => ipcRenderer.invoke('metrics-generate', data),
  metricsRunJql: (data) => ipcRenderer.invoke('metrics-run-jql', data),
  metricsSaveFilter: (data) => ipcRenderer.invoke('metrics-save-filter', data),
  runSkill: (data) => ipcRenderer.invoke('run-skill', data),
  exportPdf: (data) => ipcRenderer.invoke('export-pdf', data),
  generateDocxReport: (data) => ipcRenderer.invoke('generate-docx-report', data),
  fetchIssueSummary: (data) => ipcRenderer.invoke('fetch-issue-summary', data),
  createQaSubtask: (data) => ipcRenderer.invoke('create-qa-subtask', data),
  aiGenerateBug: (data) => ipcRenderer.invoke('ai-generate-bug', data),
  createJiraBug: (data) => ipcRenderer.invoke('create-jira-bug', data),
  importQaReport: (data) => ipcRenderer.invoke('import-qa-report', data),
  scanRepoKeys: () => ipcRenderer.invoke('scan-repo-keys'),
  clearScanCache: () => ipcRenderer.invoke('clear-scan-cache'),
  getFolderTestCases: (data) => ipcRenderer.invoke('get-folder-test-cases', data),
  getZephyrFoldersForCoverage: () => ipcRenderer.invoke('get-zephyr-folders-for-coverage'),
  listSkillTeams: () => ipcRenderer.invoke('list-skill-teams'),
})
